- hosts: all_servers
  become: yes
  tasks:
    - name: 필수 패키지 설치
      apt:
        name:
          - build-essential
          - libncurses-dev
          - libssl-dev
          - libsqlite3-dev
          - tk-dev
          - libgdbm-dev
          - libc6-dev
          - libbz2-dev
          - libffi-dev
          - zlib1g-dev
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Python 3.13.5 다운로드
      get_url:
        url: https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tgz
        dest: /tmp/Python-3.13.5.tgz

    - name: 압축 해제
      unarchive:
        src: /tmp/Python-3.13.5.tgz
        dest: /tmp/
        remote_src: yes

    - name: configure 실행
      command: ./configure --enable-optimizations
      args:
        chdir: /tmp/Python-3.13.5
        creates: /tmp/Python-3.13.5/Makefile

    - name: make 실행
      command: make -j"{{ ansible_processor_cores | default(2) }}"
      args:
        chdir: /tmp/Python-3.13.5
        creates: /tmp/Python-3.13.5/python

    - name: make altinstall 실행
      command: make altinstall
      args:
        chdir: /tmp/Python-3.13.5
        creates: /usr/local/bin/python3.13

    - name: 심볼릭 링크 생성 (python, pip)
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: '/usr/local/bin/python3.13', dest: '/usr/bin/python' }
        - { src: '/usr/local/bin/pip3.13', dest: '/usr/bin/pip' }

    - name: 설치된 Python 버전 확인
      command: python --version
      register: python_version_output
      changed_when: false

    - debug:
        msg: "설치된 파이썬 버전: {{ python_version_output.stdout }}"

